# Site settings
title: Wendy Smoak
email: wsmoak@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wsmoak.net" # the base hostname & protocol for your site
twitter_username: wsmoak
github_username:  wsmoak

# Build settings
markdown: kramdown

tag_page_layout: tag
tag_page_dir: tag

tag_feed_layout: tag_feed
tag_feed_dir: tag

highlighter: pygments

port: 3050
